language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update
- sudo apt-get install libgtest-dev
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- sudo apt-get install google-mock
- "cd /usr/src/gmock && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script:
- cd ${TRAVIS_BUILD_DIR}/RingBuffer/test
- cmake .
- make
- cd ${TRAVIS_BUILD_DIR}/AsyncComm/test
- cmake .
- make
